### PR TITLE
upcloud: encrypted at rest volumes

### PR DESCRIPTION
**Pull request by robinAwallace**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

Im creating tihs PR for reviews and then I will create a PR upstream. 

1. Adds support for encrypted bootdisks for vms
2. Bump the upcloud csi driver and added more default storage classes.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by Elias-elastisys — APPROVED** [review]

**Review by Xartos — APPROVED** [review]

**Comment by Xartos** [comment]
Make sure to update the branch before merging. @davidumea has done some changes there, so they don't dissapear

**Comment by robinAwallace** [comment]
@Elias-elastisys I updated how snapshot classes are added/created. So please take another look :slightly_smiling_face:

**Review by Elias-elastisys — COMMENTED** [review]
What about the removed Velero label? The docs seemed to indicate it was required, but never tested without it. Or do we plan to add it back somewhere else?

**Comment by robinAwallace** [comment]
> What about the removed Velero label? The docs seemed to indicate it was required, but never tested without it. Or do we plan to add it back somewhere else?

As velero is not a kubespray component it is strange to have it here. As it should be possible to chnage it to what ever. So it is possible to add the label via group_vars instead. Where I think it should live.

Example would be:

```
snapshot_classes:
  - name: upcloud-csi-snapshotclass
    is_default: true
    labels:
      velero.io/csi-volumesnapshot-class: "true"
```

**Review by Elias-elastisys — APPROVED** [review]
Yeah makes sense, lgtm!

**Pull request merged**
