### PR TITLE
Add support for LB in upcloud private zone

### PR DESCRIPTION
**Pull request by davidumea**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by davidumea** [comment]
Please let me know if I should close this and upstream it instead, if we don't want to merge it to our fork

**Comment by robinAwallace** [comment]
I would say, push it to a branch with latest version + this. And then do a upstream PR. 
So we can use this now and then next real release we can use the upstream.

**Comment by davidumea** [comment]
> I would say, push it to a branch with latest version + this. And then do a upstream PR. So we can use this now and then next real release we can use the upstream.

I have that here https://github.com/elastisys/kubespray/tree/v2.24.1%2Bk8s_node_inconsistencies_fix%2Bterraform_openstack_mission_provider%2Bupcloud-private-zone

**Comment by robinAwallace** [comment]
Nice :+1: Then push it upstream instead. We do not really want to push stuff to main here.

**Pull request closed without merging**
